# Transform Sales Data

In [ ]:
import pandas as pd
import kagglehub

# order_data = pd.read_csv('order_dataset.csv')

# marketing_data = pd.read_csv('Social_Media_Advertising.csv')

path_order_data = kagglehub.dataset_download("yaminh/product-sales-and-returns-dataset")
path_marketing_data = kagglehub.dataset_download("jsonk11/social-media-advertising-dataset")

order_data = pd.read_csv(path_order_data)

marketing_data = pd.read_csv(path_marketing_data)

marketing_data

,Campaign_ID,Target_Audience,Campaign_Goal,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Company
0,529013,Men 35-44,Product Launch,15 Days,Instagram,0.15,$500.00,5.790000,Las Vegas,Spanish,500,3000,7,Health,2022-02-25,Aura Align
1,275352,Women 45-60,Market Expansion,15 Days,Facebook,0.01,$500.00,7.210000,Los Angeles,French,500,3000,5,Home,2022-05-12,Hearth Harmony
2,692322,Men 45-60,Product Launch,15 Days,Instagram,0.08,$500.00,0.430000,Austin,Spanish,500,3000,9,Technology,2022-06-19,Cyber Circuit
3,675757,Men 25-34,Increase Sales,15 Days,Pinterest,0.03,$500.00,0.909824,Miami,Spanish,293,1937,1,Health,2022-09-08,Well Wish
4,535900,Men 45-60,Market Expansion,15 Days,Pinterest,0.13,$500.00,1.422828,Austin,French,293,1937,1,Home,2022-08-24,Hearth Harmony
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,565525,Men 25-34,Market Expansion,60 Days,Instagram,0.14,$15000.00,4.950000,Los Angeles,English,39999,119998,7,Technology,2022-10-17,Code Crafters
299996,539680,Women 25-34,Market Expansion,60 Days,Instagram,0.08,$15000.00,3.410000,Austin,Spanish,39999,119998,8,Technology,2022-02-25,Innovate Infinity
299997,140032,Women 35-44,Brand Awareness,60 Days,Pinterest,0.09,$15000.00,0.904461,Miami,French,23492,77476,1,Food,2022-10-02,Gastronomy Guild
299998,161067,Women 18-24,Market Expansion,60 Days,Instagram,0.13,$15000.00,7.430000,Las Vegas,Spanish,39999,119999,10,Food,2022-01-24,Savor Street
299999,420183,Men 25-34,Brand Awareness,60 Days,Facebook,0.08,$15000.00,1.900000,Miami,English,40000,120000,10,Technology,2022-07-18,Innovate Infinity

In [2]:
items = order_data.groupby('Item Name').size().reset_index(name='Anzahl der Zeilen')

categories = order_data.groupby('Item Name').size().reset_index(name='Anzahl der Zeilen')

companies = marketing_data.groupby('Company').size().reset_index(name='Anzahl der Zeilen')

items

   Item Name  Anzahl der Zeilen
0        AYN               3430
1        AZN                582
2        BKT                108
3        CLH               1288
4        CRH                571
5        DAL                 87
6        DFH                 73
7        DPR                266
8        EKJ                213
9        ELV                277
10       EXR                771
11       EYV                428
12       FMR                419
13       FQD                713
14       FTU                866
15       HZX                711
16       INU                490
17       JAF                528
18       JYJ                309
19       KDP                752
20       KNB               3384
21       LPZ                719
22       LQS               2591
23       MAG                384
24       MTW               1057
25       NMA               2892
26       NSP                894
27       NWB               1249
28       OHR               1397
29       OJN                 99
30       OTH               2072
31       OUT                567
32       OVT                522
33       PRT                  2
34       QID               3644
35       QMB                778
36       RIH                606
37       RJF               4665
38       RJK                541
39       TSH               1345
40       UQJ                679
41       VTH                 93
42       VXH                910
43       WHX              12320
44       XEB               4010
45       YMR                689
46       YQX               7749
47       YYI                419
48       ZQV                893

In [3]:
new_products = [
    "Smartphone", "Laptop", "Tablet", "Smartwatch", "Bluetooth-KopfhÃ¶rer", "Gaming-Konsole",
    "Externe Festplatte", "USB-Stick", "Smart-TV", "Soundbar", "Digitalkamera", "E-Book-Reader",
    "Gaming-Maus", "Gaming-Tastatur", "Monitor", "Drucker", "Scanner", "Heim-Router",
    "Smart Home Hub", "Action-Kamera", "Drohne", "Lautsprecher (tragbar)", "VR-Headset", "Mikrofon",
    "Webcam", "Powerbank", "Ladestation", "Smarte GlÃ¼hbirnen", "Elektrischer Fotorahmen", "NAS-System",
    "Netzteil", "VerlÃ¤ngerungskabel", "Beamer", "Projektor-Leinwand", "Elektronische Waage", "Digitale Wetterstation",
    "Kabelmanagement-LÃ¶sung", "Saugroboter", "Smarte Steckdose", "3D-Drucker", "RFID-Blocker",
    "Video-TÃ¼rsprechanlage", "Smartes Thermostat", "Luftreiniger", "Smartes TÃ¼rschloss", "Gaming-Stuhl",
    "Festnetztelefon", "Bluetooth-Tracker (z.B. fÃ¼r SchlÃ¼ssel)"
]

new_categories = [
    "Smartphones und Wearables",
    "Tablets und E-Reader",
    "Laptops und Notebooks",
    "Computer-ZubehÃ¶r",
    "Monitore und Bildschirme",
    "Audio und KopfhÃ¶rer",
    "Fotografie",
    "Videotechnik",
    "Gaming-GerÃ¤te",
    "Drucker und Scanner",
    "Netzwerk und Router",
    "Smart Home Hubs",
    "Smarte Beleuchtung",
    "HaushaltsgerÃ¤te",
    "Speichermedien",
    "Stromversorgung",
    "Sicherheitstechnik",
    "Tracking und Ortung",
    "Thermostate und Klimasteuerung",
    "ZubehÃ¶r fÃ¼r elektronische GerÃ¤te",
    "3D-Drucker und ZubehÃ¶r",
    "Festnetztelefonie",
]

return_reasons = [
    "Defekt bei der Lieferung", "Nicht funktionstÃ¼chtig", "Falsches Produkt geliefert",
    "Produkt entspricht nicht der Beschreibung", "Fehlende Teile", "BeschÃ¤digung nach kurzer Nutzung",
    "InkompatibilitÃ¤t", "Schlechter Zustand der Verpackung", "Batterieprobleme", "Softwarefehler",
    "VerarbeitungsqualitÃ¤t", "Ãœberhitzung", "Fehlende Dokumentation", "GerÃ¤t ist schwer zu bedienen",
    "Besseres Produkt gefunden", "Ã„sthetische MÃ¤ngel", "Unzufriedenheit mit der Leistung",
    "GerÃ¤uschentwicklung", "Falsche Farbe oder Modell", "Probleme mit dem ZubehÃ¶r"
]

In [4]:
import random


unique_item_names = order_data['Item Name'].unique()
item_name_mapping = {old_name: new_name for old_name, new_name in zip(unique_item_names, new_products)}

unique_category_names = order_data['Category'].unique()
item_category_mapping = {old_name: new_name for old_name, new_name in zip(unique_category_names, new_categories)}

order_data['Item Name'] = order_data['Item Name'].map(item_name_mapping)
order_data['Category'] = order_data['Category'].map(item_category_mapping)

order_data['Return Reason'] = order_data['Refunded Item Count'].apply(
    lambda x: random.choice(return_reasons) if x != 0 else None
)

order_data

,Item Name,Category,Version,Item Code,Item ID,Buyer ID,Transaction ID,Date,Final Quantity,Total Revenue,Price Reductions,Refunds,Final Revenue,Sales Tax,Overall Revenue,Refunded Item Count,Purchased Item Count,Return Reason
0,Smartphone,Smartphones und Wearables,32 / B / 30,27-0CD-F44-7E1-0-2F608D7,46567054.0,3301861.0,5.363560e+13,14/04/2019,1,74.17,0.00,0.00,74.17,14.83,89.0,0,1,None
1,Laptop,Tablets und E-Reader,32 / B / FtO,37-9D1-AC6-D48-E-F2D4507,16345004.0,1205940.0,4.759180e+13,14/02/2019,-1,0.00,0.00,-79.17,-79.17,-15.83,-95.0,-1,0,Produkt entspricht nicht der Beschreibung
2,Tablet,Tablets und E-Reader,32 / B / FtO,85-2EB-163-D62-5-FC50316,26246865.0,3342830.0,9.211720e+13,28/11/2018,-1,0.00,0.00,-74.17,-74.17,-14.83,-89.0,-1,0,Ãœberhitzung
3,Smartwatch,Tablets und E-Reader,33 / B / FtO,3D-687-99C-14F-4-661E2E7,42015157.0,7251983.0,5.987730e+13,3/3/2019,1,79.17,0.00,0.00,79.17,15.83,95.0,0,1,None
4,Bluetooth-KopfhÃ¶rer,Laptops und Notebooks,34 / B / FtO,F9-9FA-787-104-B-DCEE379,40522014.0,9940388.0,3.658240e+13,26/11/2018,1,74.17,0.00,0.00,74.17,14.83,89.0,0,1,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70047,Smartwatch,Tablets und E-Reader,36 / B / FtO,7C-D23-B98-39F-E-93ABC5C,56109013.0,3421398.0,1.498000e+13,20/11/2018,1,79.16,0.00,0.00,79.16,15.84,95.0,0,1,None
70048,USB-Stick,Tablets und E-Reader,33 / A / FtO,10-D34-C89-3B7-8-77333AA,35445869.0,1913362.0,1.506840e+13,3/4/2019,1,79.16,-7.91,0.00,71.25,14.25,85.5,0,1,None
70049,Heim-Router,Laptops und Notebooks,34 / A / FtO,EA-048-158-A25-3-11DAA3E,27215940.0,9781863.0,6.776480e+13,26/12/2018,1,51.67,0.00,0.00,51.67,10.33,62.0,0,1,None
70050,Smart-TV,Tablets und E-Reader,36 / B / FtO,89-517-B97-D81-B-F23CCC1,89883040.0,6808059.0,2.156440e+13,12/1/2019,1,55.00,0.00,0.00,55.00,11.00,66.0,0,1,None
70051,Smart Home Hub,Smartphones und Wearables,36 / B / 32,08-E8A-524-409-1-7A032D2,11926413.0,3582530.0,6.202560e+13,17/11/2018,1,74.16,0.00,0.00,74.16,14.84,89.0,0,1,None

In [5]:
unique_company_names = marketing_data['Company'].unique()
item_company_mapping = {old_name: new_name for old_name, new_name in zip(unique_company_names, new_products)}


marketing_data['Company'] = marketing_data['Company'].map(item_company_mapping)
marketing_data.rename(columns={'Company': 'Product'}, inplace=True)
marketing_data

,Campaign_ID,Target_Audience,Campaign_Goal,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Product
0,529013,Men 35-44,Product Launch,15 Days,Instagram,0.15,$500.00,5.790000,Las Vegas,Spanish,500,3000,7,Health,2022-02-25,Smartphone
1,275352,Women 45-60,Market Expansion,15 Days,Facebook,0.01,$500.00,7.210000,Los Angeles,French,500,3000,5,Home,2022-05-12,Laptop
2,692322,Men 45-60,Product Launch,15 Days,Instagram,0.08,$500.00,0.430000,Austin,Spanish,500,3000,9,Technology,2022-06-19,Tablet
3,675757,Men 25-34,Increase Sales,15 Days,Pinterest,0.03,$500.00,0.909824,Miami,Spanish,293,1937,1,Health,2022-09-08,Smartwatch
4,535900,Men 45-60,Market Expansion,15 Days,Pinterest,0.13,$500.00,1.422828,Austin,French,293,1937,1,Home,2022-08-24,Laptop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,565525,Men 25-34,Market Expansion,60 Days,Instagram,0.14,$15000.00,4.950000,Los Angeles,English,39999,119998,7,Technology,2022-10-17,Bluetooth-Tracker (z.B. fÃ¼r SchlÃ¼ssel)
299996,539680,Women 25-34,Market Expansion,60 Days,Instagram,0.08,$15000.00,3.410000,Austin,Spanish,39999,119998,8,Technology,2022-02-25,RFID-Blocker
299997,140032,Women 35-44,Brand Awareness,60 Days,Pinterest,0.09,$15000.00,0.904461,Miami,French,23492,77476,1,Food,2022-10-02,Scanner
299998,161067,Women 18-24,Market Expansion,60 Days,Instagram,0.13,$15000.00,7.430000,Las Vegas,Spanish,39999,119999,10,Food,2022-01-24,Webcam
299999,420183,Men 25-34,Brand Awareness,60 Days,Facebook,0.08,$15000.00,1.900000,Miami,English,40000,120000,10,Technology,2022-07-18,RFID-Blocker

In [6]:
marketing_data.to_csv('marketing_data.csv', index=False)
order_data.to_csv('order_data.csv', index=False)